### PR TITLE
Use the new Castle.Core CaptureProceedInfo() to make AsyncInterceptor work for reals

### PR DESCRIPTION
**Pull request by JSkimming**
I plan to release this as an alpha, as we feel some work is required before it is production ready.

### CODE REVIEW

**Comment by brunoblank** [comment]
@JSkimming awesome work here! 

I have a lot on my plate atm. But, I will try to find time during the weekend helping out on this!

**Comment by JSkimming** [comment]
@brunoblank Please do jump in if you can spare the time.

I've made the changes and have managed to get it all working, unfortunately, I'm getting a deadlock unless I disable parallel test execution.

If you edit the file [xunit.runner.json](https://github.com/JSkimming/Castle.Core.AsyncInterceptor/blob/866d03c357f392e73489afd0445d7f5e346cb1e2/test/Castle.Core.AsyncInterceptor.Tests/xunit.runner.json#L4-L5) on the _use-CaptureProceedInfo_ branch and change `parallelizeTestCollections` to `true`, you'll get the problem.

Every 60 seconds the _Long Running Tests_ are displayed. This shows the tests that are deadlocked.

Change `longRunningTestSeconds` in `xunit.runner.json` to a smaller number to see the deadlocked tests sooner.

I'd like to bottom out the root cause of the deadlock. It's possible this is not a new problem but is now happening because all the tests are truly executing asynchronously.

**Comment by brunoblank** [comment]
@JSkimming I tried to reproduce the dead-lock but everything seems to run fine for me done the changes described above.

This is the output:
```
Test run for C:\projects\Castle.Core.AsyncInterceptor\test\Castle.Core.AsyncInterceptor.Tests\bin\Debug\netcoreapp2.0\Castle.Core.AsyncInterceptor.Tests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.9.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.54] Castle.Core.AsyncInterceptor.Tests: Non-serializable data ('System.Object[]') found for 'Castle.DynamicProxy.ProxyGeneratorExtensionsShould.ExtendInterfaceProxyGenerator'; falling back to single test case.
[xUnit.net 00:00:00.55] Castle.Core.AsyncInterceptor.Tests: Non-serializable data ('System.Object[]') found for 'Castle.DynamicProxy.ProxyGeneratorExtensionsShould.ExtendClassProxyGenerator'; falling back to single test case.

Total tests: 129. Passed: 129. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 2,3822 Seconds
```
(dotnet --version: 2.2.105)

**Comment by stakx** [comment]
Same here btw. No deadlocks for me during test execution with `"parallelizeTestCollections": true`.

<details>
<summary>dotnet --info</summary>

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.202
 Commit:    8a7ff6789d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.202\

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.2.202 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```
</details>

**Comment by JSkimming** [comment]
@brunoblank, @stakx thanks for giving it a shot.

I was using .NET Core 2.2.104 though now upgraded to 2.2.202, I still get the deadlock, as sones both AppVeyor and Travis.

I've noticed both of your test runs take a little over 2 seconds, whereas mine is about 3.8, maybe there's a timing issue, which my 2-year-old laptop gets because it's slower than yours.

I'm going to see if I can identify where the deadlock is occurring.

**Comment by JSkimming** [comment]
@brunoblank, @stakx I found it.

xunit defaults `maxParallelThreads` to the number of processors. 4 on my laptop, 2 on the build servers, and I'm guessing at least 8 on your machines. I've forced it to 8 in the config, and the deadlock is gone.

> It's possible this is not a new problem but is now happening because all the tests are genuinely executing asynchronously.

I was right; it was never a problem because async before interception wasn't possible. This deadlock issue does though highlight the flaw in the implementation of `AsyncInterceptorBase`, or as I suspect, in its design.

It's trying to make it easier to implement an interceptor by requiring a derived class to implement just two methods.

```csharp
protected abstract Task InterceptAsync(IInvocation invocation, Func<IInvocation, Task> proceed);
protected abstract Task<TResult> InterceptAsync<TResult>(
    IInvocation invocation,
    Func<IInvocation, Task<TResult>> proceed);
```

But for synchronous interception, it has to transition back from a potentially asynchronous interceptor, and the only safe way (or so I thought) to do that is starting a new thread using `Task.Run()`. The reason the tests were deadlocking is that the maximum number of threads had been exhausted.

In a real scenario, the maximum number of threads will be far higher, but not unlimited, and this has the potential to deadlock in a production system, something interception is not supposed to do. Sort of like the [Hippocratic Oath](https://en.wikipedia.org/wiki/Hippocratic_Oath#%22_First_do_no_harm_%22 "Primum non nocere - first, to do no harm") 😃.

I'm keen to get this out, so I'm thinking of releasing it as an alpha, then I'd like to tackle `AsyncInterceptorBase`.

**Comment by brunoblank** [comment]
Glad you found it! 

That makes sense now when you identified it. We should remove all blocking calls from the library as it will cause thread exhaustion (or really bad performance when the thread pool is scaling up).

It is important that we realize running synchronous (cpu-bound) interceptions is totally fine even if it return like `Thread.FromResult` even though there is the cost of an extra Task allocation. 

The big problem is running blocking call on async or the slightly better running async and waiting (using a Task.Run). We should not try to safeguard against this.

> I'm keen to get this out, so I'm thinking of releasing it as an alpha, then I'd like to tackle AsyncInterceptorBase.

Totally agree

**Pull request merged**
